version: 2

models:
  - name: verify_money_to_words_en
    enabled: {{ target.type in ['snowflake', 'sqlserver'] }}
    tests:
      - dbt_utils.expression_is_true:
          expression: 'actual = expected'