name: dbt compile

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-test:dbt-py3.10

    services:
      sqlserver:
        image: ghcr.io/${{ github.repository }}:sqlserver-2022
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 5atyaNadell@

    env:
      SQLSERVER_HOST: sqlserver
      SQLSERVER_PORT: 1433
      SQLSERVER_DATABASE: msdb
      SQLSERVER_USER: sa
      SQLSERVER_PASSWORD: 5atyaNadell@
      SQLSERVER_SCHEMA: PR_${{ github.sha }}
      DBT_PROFILES_DIR: ./profiles

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: |
          dbt deps
          dbt compile
        working-directory: integration_tests

      - uses: actions/upload-artifact@v3
        with:
          name: dbt-artifact
          path: integration_tests/target/