# This is a basic workflow to help you get started with Actions

name: integration_tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9.6'

      - name: Install dbt
        run: |
          cd integration_tests
          python -m pip install poetry
          python -m poetry install --no-dev

      - name: Setup profiles
        run: |
          mkdir ~/.dbt > /dev/null
          cp integration_tests/profiles/profiles.yml ~/.dbt/profiles.yml

      - name: Execute test - Snowflake
        working-directory: ./integration_tests
        run: |
          poetry run dbt run --target snowflake
          poetry run dbt test --target snowflake
        env:
          SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.SNOWFLAKE_TEST_ACCOUNT }}
          SNOWFLAKE_TEST_USER: ${{ secrets.SNOWFLAKE_TEST_USER }}
          SNOWFLAKE_TEST_PASSWORD: ${{ secrets.SNOWFLAKE_TEST_PASSWORD }}
          SNOWFLAKE_TEST_ROLE: SYSADMIN
          SNOWFLAKE_TEST_DATABASE: DEMO
          SNOWFLAKE_TEST_WAREHOUSE: COMPUTE_WH

      # - name: Execute test - SQLSERVER
      #   working-directory: ./integration_tests
      #   run: |
      #     poetry run dbt run --target snowflake
      #     poetry run dbt test --target snowflake
      #   env:
      #     SQLSERVER_HOST: ${{ secrets.SQLSERVER_HOST }}
      #     SQLSERVER_PORT: 1433
      #     SQLSERVER_USER: ${{ secrets.SQLSERVER_USER }}
      #     SQLSERVER_PASSWORD: ${{ secrets.SQLSERVER_PASSWORD }}
      #     SQLSERVER_DATABASE: DEMO

      - name: Publish docs
        working-directory: ./integration_tests
        run: |
          poetry run dbt docs generate
          echo "<< Publish to somewhere here >>"
