# This is a basic workflow to help you get started with Actions

name: integration_tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9.6'

      - name: Install dbt
        run: |
          cd integration_tests
          python -m pip install poetry
          python -m poetry install --no-dev

      - name: Setup profiles
        run: |
          mkdir ~/.dbt > /dev/null
          cp integration_tests/profiles/profiles.yml ~/.dbt/profiles.yml

      - name: Execute test
        run: |
          cd integration_tests
          dbt run
          dbt test

      - name: Publish docs
        run: |
          cd integration_tests
          dbt docs generate
          echo "<< Publish to somewhere here >>"
