name: power 6/55 daily forecast

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  build-and-alert:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/datnguye/dbt-resto:power655forecast-2023
    services:
      sqlserver:
        image: ghcr.io/datnguye/dbt-resto:sqlserver-2022
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 5atyaNadell@

    env:
      SQLSERVER_HOST: sqlserver
      SQLSERVER_PORT: 1433
      SQLSERVER_DATABASE: msdb
      SQLSERVER_USER: sa
      SQLSERVER_PASSWORD: 5atyaNadell@
      SQLSERVER_SCHEMA: resto
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      DBT_PROFILES_DIR: ./profiles # working-directory: integration_tests

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          key: poetry-cache-${{ runner.os }}-${{ github.ref }}
          path: ~/.cache/pypoetry

      - name: Install dbt
        run: |
          poetry install --no-dev
          poetry run dbt deps
        working-directory: integration_tests

      - name: Data Ingestion
        run: |
          mongoexport --uri="${MONGODB_URI}" \
            --collection=data \
            --type=csv \
            --fields=box_date,box_id,box_name,box_result_numbers,box_results,created_at,updated_at \
            --out=./seeds/vietlot/power655/vietlot_power655_data.csv

      - name: Data Transformation
        run: |
          poetry run dbt seed
          poetry run dbt run -s +fact_number_forecast
        working-directory: integration_tests

      - name: Notification
        run: poetry run python jobs/send_forecast.py
        working-directory: integration_tests
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_MAILING_LIST: ${{ secrets.SENDGRID_MAILING_LIST }}