name: power 6/55 ingestion

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update /seeds/vietlot/power655
        uses: ./.github/actions/power655-ingestion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}