name: power 6/55 daily forecast

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sqlserver_version: ["2022"]
    container:
      image: ghcr.io/dbt-msft/dbt-sqlserver:CI-3.10-msodbc18
    services:
      sqlserver:
        image: ghcr.io/dbt-msft/dbt-sqlserver:server-${{ matrix.sqlserver_version }}
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 5atyaNadell@

    env:
      SQLSERVER_HOST: sqlserver
      SQLSERVER_PORT: 1433
      SQLSERVER_DATABASE: msdb
      SQLSERVER_USER: sa
      SQLSERVER_PASSWORD: 5atyaNadell@
      SQLSERVER_SCHEMA: docs

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9.6'

      - name: Install dbt
        run: |
          pip install poetry
          export DBT_PROFILES_DIR=./profiles
          poetry install --no-dev
          poetry run dbt deps
        working-directory: integration_tests

      - name: Transformation
        run: poetry run dbt build -s package:dbt_resto
        working-directory: integration_tests

      - name: Report
        run: poetry run python jobs/send_email.py
        working-directory: integration_tests