name: power 6/55 daily forecast

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  build-and-alert:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/dbt-msft/dbt-sqlserver:CI-3.10-msodbc18
    services:
      sqlserver:
        image: ghcr.io/dbt-msft/dbt-sqlserver:server-2022
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 5atyaNadell@

    env:
      SQLSERVER_HOST: sqlserver
      SQLSERVER_PORT: 1433
      SQLSERVER_DATABASE: msdb
      SQLSERVER_USER: sa
      SQLSERVER_PASSWORD: 5atyaNadell@
      SQLSERVER_SCHEMA: docs
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install mongodb tools
        run: |
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.7.0.deb
          apt install ./mongodb-database-tools-*-100.7.0.deb

      - name: Install dbt
        run: |
          pip install poetry
          export DBT_PROFILES_DIR=./profiles
          poetry install --no-dev
          poetry run dbt deps
        working-directory: integration_tests

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Data Ingestion
        run: |
          mongoexport --uri="${MONGODB_URI}" \
            --collection=data \
            --type=csv \
            --fields=box_date,box_id,box_name,box_result_numbers,box_results,created_at,updated_at \
            --out=./seeds/vietlot/power655/vietlot_power655_data.csv

      - name: Data Transformation
        run: poetry run dbt build -s package:dbt_resto
        working-directory: integration_tests

      - name: Notification
        run: poetry run python jobs/send_forecast.py
        working-directory: integration_tests