---
name: publish docker images for dbt test
on:
  push:
    paths:
      - 'devops/test.Dockerfile'
      - '.github/workflows/publish-docker-dbt-test.yml'
    branches:
      - 'main'

jobs:
  publish-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ["3.10"]
        dbt_version: ["1.3"]

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: log in to the container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./
          build-args: |
            "PYTHON_VERSION=${{ matrix.python_version }}"
            "DBT_VERSION=${{ matrix.dbt_version }}"
          file: devops/test.Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}-test:dbt-py${{ matrix.python_version }}