version: 2

macros:
  - name: get_table_alias
    description: |
      Suffix the table name with your configured variable `table_suffix`.
    docs:
      show: true
    arguments:
      - name: relation
        type: relation object
        description: Model object to alias

  - name: default__get_table_alias
    docs:
      show: false